[Run 1] 2024/10/16 8:40:21 (23:40:21.375Z): Fatal error: TypeError: Cannot set properties of undefined (setting 'onopen')
[Run 1] 2024/10/16 8:40:44 (23:40:44.515Z): Fatal error: TypeError: Cannot set properties of undefined (setting 'onopen')
[Run 1] 2024/10/16 8:43:02 (23:43:02.594Z): Fatal error: TypeError: Cannot set properties of undefined (setting 'onopen')
[Run 1] 2024/10/16 8:43:56 (23:43:56.095Z): Contract instance created
[Run 2] 2024/10/16 8:43:57 (23:43:57.711Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 3] 2024/10/16 8:43:57 (23:43:57.975Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 4] 2024/10/16 8:43:57 (23:43:57.977Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 5] 2024/10/16 8:43:57 (23:43:57.981Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 6] 2024/10/16 8:43:57 (23:43:57.982Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 7] 2024/10/16 8:43:57 (23:43:57.997Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 8] 2024/10/16 8:43:57 (23:43:57.997Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 9] 2024/10/16 8:43:57 (23:43:57.998Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 10] 2024/10/16 8:43:57 (23:43:57.999Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 11] 2024/10/16 8:43:58 (23:43:58.034Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 12] 2024/10/16 8:43:58 (23:43:58.035Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 13] 2024/10/16 8:43:58 (23:43:58.051Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 14] 2024/10/16 8:43:58 (23:43:58.053Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 15] 2024/10/16 8:43:58 (23:43:58.053Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 16] 2024/10/16 8:43:58 (23:43:58.054Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 17] 2024/10/16 8:43:58 (23:43:58.064Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 18] 2024/10/16 8:43:58 (23:43:58.067Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 19] 2024/10/16 8:43:58 (23:43:58.096Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 20] 2024/10/16 8:43:58 (23:43:58.097Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 21] 2024/10/16 8:43:58 (23:43:58.099Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 22] 2024/10/16 8:43:58 (23:43:58.117Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 23] 2024/10/16 8:43:58 (23:43:58.117Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 24] 2024/10/16 8:43:58 (23:43:58.136Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 25] 2024/10/16 8:43:58 (23:43:58.137Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 26] 2024/10/16 8:43:58 (23:43:58.143Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 27] 2024/10/16 8:43:58 (23:43:58.164Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 28] 2024/10/16 8:43:58 (23:43:58.164Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 29] 2024/10/16 8:43:58 (23:43:58.165Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 30] 2024/10/16 8:43:58 (23:43:58.176Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 31] 2024/10/16 8:43:58 (23:43:58.186Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 32] 2024/10/16 8:43:58 (23:43:58.191Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 33] 2024/10/16 8:43:58 (23:43:58.209Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 34] 2024/10/16 8:43:58 (23:43:58.209Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 35] 2024/10/16 8:43:58 (23:43:58.210Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":62,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 36] 2024/10/16 8:43:58 (23:43:58.210Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":64,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 37] 2024/10/16 8:43:58 (23:43:58.211Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":73,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 38] 2024/10/16 8:43:58 (23:43:58.211Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":74,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 39] 2024/10/16 8:43:58 (23:43:58.212Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":59,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 40] 2024/10/16 8:43:58 (23:43:58.212Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":80,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 41] 2024/10/16 8:43:58 (23:43:58.213Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":60,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 42] 2024/10/16 8:43:58 (23:43:58.214Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":72,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 43] 2024/10/16 8:43:58 (23:43:58.214Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":83,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 44] 2024/10/16 8:43:58 (23:43:58.215Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":79,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 45] 2024/10/16 8:43:58 (23:43:58.215Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":78,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 46] 2024/10/16 8:43:58 (23:43:58.216Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":65,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 47] 2024/10/16 8:43:58 (23:43:58.216Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":68,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 48] 2024/10/16 8:43:58 (23:43:58.217Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":66,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 49] 2024/10/16 8:43:58 (23:43:58.217Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":82,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 50] 2024/10/16 8:43:58 (23:43:58.217Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":69,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 51] 2024/10/16 8:43:58 (23:43:58.218Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":76,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 52] 2024/10/16 8:43:58 (23:43:58.218Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":61,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 53] 2024/10/16 8:43:58 (23:43:58.219Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":67,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 54] 2024/10/16 8:43:58 (23:43:58.252Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":77,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 55] 2024/10/16 8:43:58 (23:43:58.253Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":75,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 56] 2024/10/16 8:43:58 (23:43:58.253Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":70,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 57] 2024/10/16 8:43:58 (23:43:58.253Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":81,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 58] 2024/10/16 8:43:58 (23:43:58.254Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":63,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 59] 2024/10/16 8:43:58 (23:43:58.254Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":84,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 60] 2024/10/16 8:43:58 (23:43:58.254Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":101,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 61] 2024/10/16 8:43:58 (23:43:58.255Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 62] 2024/10/16 8:43:58 (23:43:58.255Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 63] 2024/10/16 8:43:58 (23:43:58.255Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":71,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 64] 2024/10/16 8:43:58 (23:43:58.256Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":94,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 65] 2024/10/16 8:43:58 (23:43:58.257Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":88,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 66] 2024/10/16 8:43:58 (23:43:58.257Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":92,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 67] 2024/10/16 8:43:58 (23:43:58.257Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":90,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 68] 2024/10/16 8:43:58 (23:43:58.258Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":100,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 69] 2024/10/16 8:43:58 (23:43:58.258Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":85,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 70] 2024/10/16 8:43:58 (23:43:58.258Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":87,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 71] 2024/10/16 8:43:58 (23:43:58.259Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":96,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 72] 2024/10/16 8:43:58 (23:43:58.259Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":89,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 73] 2024/10/16 8:43:58 (23:43:58.259Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":93,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 74] 2024/10/16 8:43:58 (23:43:58.260Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":98,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 75] 2024/10/16 8:43:58 (23:43:58.260Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":91,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 76] 2024/10/16 8:43:58 (23:43:58.282Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 77] 2024/10/16 8:43:58 (23:43:58.283Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":95,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 78] 2024/10/16 8:43:58 (23:43:58.283Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":99,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 79] 2024/10/16 8:43:58 (23:43:58.284Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 80] 2024/10/16 8:43:58 (23:43:58.284Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":97,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 81] 2024/10/16 8:43:58 (23:43:58.284Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 82] 2024/10/16 8:43:58 (23:43:58.285Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":86,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 83] 2024/10/16 8:43:58 (23:43:58.285Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 84] 2024/10/16 8:43:58 (23:43:58.285Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 85] 2024/10/16 8:43:58 (23:43:58.286Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 86] 2024/10/16 8:43:58 (23:43:58.349Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 87] 2024/10/16 8:43:58 (23:43:58.350Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 88] 2024/10/16 8:43:58 (23:43:58.351Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 89] 2024/10/16 8:43:58 (23:43:58.352Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 90] 2024/10/16 8:43:58 (23:43:58.372Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 91] 2024/10/16 8:43:58 (23:43:58.373Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 92] 2024/10/16 8:43:58 (23:43:58.373Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 93] 2024/10/16 8:43:58 (23:43:58.374Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 94] 2024/10/16 8:43:58 (23:43:58.375Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 95] 2024/10/16 8:43:58 (23:43:58.376Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 96] 2024/10/16 8:43:58 (23:43:58.414Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 97] 2024/10/16 8:43:58 (23:43:58.414Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 98] 2024/10/16 8:43:58 (23:43:58.416Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 99] 2024/10/16 8:43:58 (23:43:58.423Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 100] 2024/10/16 8:43:58 (23:43:58.448Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 101] 2024/10/16 8:43:58 (23:43:58.448Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 102] 2024/10/16 8:43:58 (23:43:58.752Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":102,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 103] 2024/10/16 8:43:58 (23:43:58.805Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":104,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 104] 2024/10/16 8:43:58 (23:43:58.806Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":103,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 105] 2024/10/16 8:43:58 (23:43:58.807Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":105,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 106] 2024/10/16 8:43:58 (23:43:58.829Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":106,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 107] 2024/10/16 8:43:58 (23:43:58.846Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":107,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 108] 2024/10/16 8:43:58 (23:43:58.884Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":109,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 109] 2024/10/16 8:43:58 (23:43:58.886Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":108,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 110] 2024/10/16 8:43:58 (23:43:58.901Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":110,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 111] 2024/10/16 8:43:58 (23:43:58.908Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":111,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 112] 2024/10/16 8:43:58 (23:43:58.937Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":112,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 113] 2024/10/16 8:43:58 (23:43:58.938Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":113,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 114] 2024/10/16 8:43:58 (23:43:58.974Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":115,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 115] 2024/10/16 8:43:58 (23:43:58.976Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":114,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 116] 2024/10/16 8:43:59 (23:43:59.017Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":116,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 117] 2024/10/16 8:43:59 (23:43:59.074Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 118] 2024/10/16 8:43:59 (23:43:59.084Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 119] 2024/10/16 8:43:59 (23:43:59.094Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 120] 2024/10/16 8:43:59 (23:43:59.106Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 121] 2024/10/16 8:43:59 (23:43:59.126Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 122] 2024/10/16 8:43:59 (23:43:59.128Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 123] 2024/10/16 8:43:59 (23:43:59.154Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 124] 2024/10/16 8:43:59 (23:43:59.155Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 125] 2024/10/16 8:43:59 (23:43:59.174Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 126] 2024/10/16 8:43:59 (23:43:59.215Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 127] 2024/10/16 8:43:59 (23:43:59.215Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 128] 2024/10/16 8:43:59 (23:43:59.242Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 129] 2024/10/16 8:43:59 (23:43:59.243Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 130] 2024/10/16 8:43:59 (23:43:59.266Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 131] 2024/10/16 8:43:59 (23:43:59.267Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 132] 2024/10/16 8:43:59 (23:43:59.306Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 133] 2024/10/16 8:43:59 (23:43:59.307Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 134] 2024/10/16 8:43:59 (23:43:59.329Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 135] 2024/10/16 8:43:59 (23:43:59.336Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 136] 2024/10/16 8:43:59 (23:43:59.363Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 137] 2024/10/16 8:43:59 (23:43:59.364Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 138] 2024/10/16 8:43:59 (23:43:59.378Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 139] 2024/10/16 8:43:59 (23:43:59.414Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 140] 2024/10/16 8:43:59 (23:43:59.414Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 141] 2024/10/16 8:43:59 (23:43:59.438Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 142] 2024/10/16 8:43:59 (23:43:59.444Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 143] 2024/10/16 8:43:59 (23:43:59.462Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 144] 2024/10/16 8:43:59 (23:43:59.469Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 145] 2024/10/16 8:43:59 (23:43:59.488Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 146] 2024/10/16 8:43:59 (23:43:59.518Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 147] 2024/10/16 8:43:59 (23:43:59.554Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 148] 2024/10/16 8:43:59 (23:43:59.554Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 149] 2024/10/16 8:43:59 (23:43:59.555Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 150] 2024/10/16 8:43:59 (23:43:59.561Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 151] 2024/10/16 8:43:59 (23:43:59.575Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 152] 2024/10/16 8:43:59 (23:43:59.607Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 153] 2024/10/16 8:43:59 (23:43:59.608Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 154] 2024/10/16 8:43:59 (23:43:59.651Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 155] 2024/10/16 8:43:59 (23:43:59.658Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 156] 2024/10/16 8:43:59 (23:43:59.677Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":157,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 157] 2024/10/16 8:43:59 (23:43:59.677Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":158,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 158] 2024/10/16 8:43:59 (23:43:59.678Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 159] 2024/10/16 8:43:59 (23:43:59.699Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":160,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 160] 2024/10/16 8:43:59 (23:43:59.701Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":159,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 161] 2024/10/16 8:43:59 (23:43:59.736Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":162,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 162] 2024/10/16 8:43:59 (23:43:59.746Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":163,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 163] 2024/10/16 8:43:59 (23:43:59.768Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":164,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 164] 2024/10/16 8:43:59 (23:43:59.769Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":161,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 165] 2024/10/16 8:43:59 (23:43:59.791Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":166,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 166] 2024/10/16 8:43:59 (23:43:59.792Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":165,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 167] 2024/10/16 8:43:59 (23:43:59.844Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":167,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 168] 2024/10/16 8:43:59 (23:43:59.845Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":168,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 169] 2024/10/16 8:43:59 (23:43:59.906Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":170,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 170] 2024/10/16 8:43:59 (23:43:59.907Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":169,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 171] 2024/10/16 8:43:59 (23:43:59.907Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":171,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 172] 2024/10/16 8:43:59 (23:43:59.939Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":173,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 173] 2024/10/16 8:43:59 (23:43:59.940Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":172,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 174] 2024/10/16 8:43:59 (23:43:59.941Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":175,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 175] 2024/10/16 8:43:59 (23:43:59.943Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":174,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 176] 2024/10/16 8:43:59 (23:43:59.998Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":176,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 177] 2024/10/16 8:43:59 (23:43:59.999Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":177,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 178] 2024/10/16 8:44:00 (23:44:00.009Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":178,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 179] 2024/10/16 8:44:00 (23:44:00.010Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":179,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 180] 2024/10/16 8:44:00 (23:44:00.022Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":180,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 181] 2024/10/16 8:44:00 (23:44:00.036Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":181,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 182] 2024/10/16 8:44:00 (23:44:00.052Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":182,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 183] 2024/10/16 8:44:00 (23:44:00.086Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":185,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 184] 2024/10/16 8:44:00 (23:44:00.087Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":183,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 185] 2024/10/16 8:44:00 (23:44:00.101Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":184,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 186] 2024/10/16 8:44:00 (23:44:00.106Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":186,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 187] 2024/10/16 8:44:00 (23:44:00.125Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":187,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 188] 2024/10/16 8:44:00 (23:44:00.132Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":188,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 189] 2024/10/16 8:44:00 (23:44:00.158Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":189,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 190] 2024/10/16 8:44:00 (23:44:00.182Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":190,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 191] 2024/10/16 8:44:00 (23:44:00.183Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":191,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 192] 2024/10/16 8:44:00 (23:44:00.194Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":192,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 193] 2024/10/16 8:44:00 (23:44:00.224Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d06000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab100000000000000000000000000000000000000000000000000000001dcd65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":193,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 194] 2024/10/16 8:44:00 (23:44:00.224Z): Transaction simulation failed or error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x6dde833Ab78b2D28D726225Ec121Cb775186Cff7","to":"0x9EeaDf27efaA9e90cf37347C57e6bdcBe9E99090","data":"0x7cff0d0600000000000000000000000082af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000006","accessList":null}, error={"code":429,"response":"{\"jsonrpc\":\"2.0\",\"id\":194,\"error\":{\"code\":429,\"message\":\"Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput\"}}"}, code=CALL_EXCEPTION, version=providers/5.7.2)
[Run 195] 2024/10/16 8:44:00 (23:44:00.277Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 196] 2024/10/16 8:44:00 (23:44:00.277Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 197] 2024/10/16 8:44:00 (23:44:00.296Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 198] 2024/10/16 8:44:00 (23:44:00.297Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 199] 2024/10/16 8:44:00 (23:44:00.329Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 200] 2024/10/16 8:44:00 (23:44:00.344Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
[Run 201] 2024/10/16 8:44:00 (23:44:00.347Z): Transaction simulation failed or error: call revert exception; VM Exception while processing transaction: reverted with reason string "Flash loan arbitrage opportunity not profitable" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="callFlash((address,address,uint256,uint256,uint256,uint256))", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002f466c617368206c6f616e20617262697472616765206f70706f7274756e697479206e6f742070726f66697461626c650000000000000000000000000000000000", errorArgs=["Flash loan arbitrage opportunity not profitable"], errorName="Error", errorSignature="Error(string)", reason="Flash loan arbitrage opportunity not profitable", code=CALL_EXCEPTION, version=abi/5.7.0)
